POST https://localhost:5001/update
content-type: application/json

{
    "token": "6838ab09-c57d-4a97-9113-c0f4c00dd5be",
    "clientStatus": "Complete",
    "GenerationsComputed": 150,
    "ResultBoard": [

    ]
}