POST https://localhost:5001/update
content-type: application/json

{
    "token": "6fadb61e-cf02-4e67-81fc-ffc76a262269",
    "GenerationsComputed": 150,
    "ResultBoard": [
        {
            "x": 1,
            "y": 1
        }
    ]
}